[package]
name = "pfuzzer"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pfuzzer"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
nucleo = "0.5.0"
pyo3 = "0.23.3"
